# Generated by Django 4.1.1 on 2022-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='지점명')),
                ('kko_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='카카오 아이디')),
                ('kko_pass', models.CharField(blank=True, max_length=128, null=True, verbose_name='카카오 비번')),
                ('reg_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agency',
            },
        ),
        migrations.CreateModel(
            name='KkoMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='지점명')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='고객명')),
                ('msg_index', models.IntegerField(default=1, verbose_name='차수')),
                ('client_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='고객번호')),
                ('kko_url', models.CharField(max_length=255, verbose_name='카카오링크')),
                ('request_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='요청일시')),
                ('result', models.CharField(blank=True, max_length=64, null=True, verbose_name='상태')),
            ],
            options={
                'verbose_name': 'KkoMsg',
                'verbose_name_plural': 'KkoMsg',
            },
        ),
        migrations.CreateModel(
            name='MsgTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('A', '공통'), ('B', '지점')], default='A', max_length=2, verbose_name='전송타입')),
                ('msg_index', models.IntegerField(default=1, verbose_name='차수')),
                ('msg_content', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
            ],
            options={
                'verbose_name': 'MsgTemplate',
                'verbose_name_plural': 'MsgTemplate',
            },
        ),
    ]
