# Generated by Django 4.1.1 on 2023-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='지점명')),
                ('kko_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='카카오 아이디')),
                ('kko_pass', models.CharField(blank=True, max_length=128, null=True, verbose_name='카카오 비번')),
                ('report_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='리포트 수신')),
                ('report_owner_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='인증담당자')),
                ('report_owner_tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='인증담당 연락처')),
                ('reg_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
            ],
            options={
                'verbose_name': '지점',
                'verbose_name_plural': '지점',
            },
        ),
        migrations.CreateModel(
            name='KkoMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='지점명')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='고객명')),
                ('msg_index', models.CharField(max_length=24, verbose_name='차수코드')),
                ('client_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='고객번호')),
                ('kko_url', models.CharField(max_length=255, verbose_name='카카오링크')),
                ('request_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('send_at', models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트')),
                ('result', models.CharField(blank=True, default='요청', max_length=64, null=True, verbose_name='상태')),
            ],
            options={
                'verbose_name': '메시지 요청',
                'verbose_name_plural': '메시지 요청',
            },
        ),
        migrations.CreateModel(
            name='MsgTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('A', '공통'), ('B', '지점')], default='A', max_length=2, verbose_name='전송타입')),
                ('msg_index', models.CharField(max_length=24, verbose_name='차수코드')),
                ('msg_content', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('img_content', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지')),
                ('link_content', models.URLField(blank=True, max_length=512, null=True, verbose_name='외부링크')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
            ],
            options={
                'verbose_name': '메시지 템플릿',
                'verbose_name_plural': '메시지 템플릿',
            },
        ),
        migrations.CreateModel(
            name='PublicMsgTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_index', models.CharField(max_length=24, verbose_name='차수코드')),
                ('msg_content', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('img_content', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지')),
                ('link_content', models.URLField(blank=True, max_length=512, null=True, verbose_name='외부링크')),
                ('start_at', models.DateTimeField(verbose_name='시작일')),
                ('end_at', models.DateTimeField(verbose_name='종료일')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
            ],
            options={
                'verbose_name': '부가 메시지 템플릿',
                'verbose_name_plural': '부가 메시지 템플릿',
            },
        ),
    ]
