# Generated by Django 4.1.1 on 2023-07-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KkoMsgEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='지점명')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='고객명')),
                ('msg_index', models.CharField(max_length=24, verbose_name='차수코드')),
                ('client_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='고객번호')),
                ('kko_url', models.CharField(max_length=255, verbose_name='카카오링크')),
                ('request_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('send_at', models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트')),
                ('result', models.CharField(blank=True, default='요청', max_length=64, null=True, verbose_name='상태')),
            ],
            options={
                'verbose_name': 'EVENT 메시지 요청',
                'verbose_name_plural': 'EVENT 메시지 요청',
            },
        ),
    ]
