# Generated by Django 4.1.1 on 2022-09-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_agency_options_alter_kkomsg_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kkomsg',
            name='id',
        ),
        migrations.AddField(
            model_name='kkomsg',
            name='msg_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
