# Generated by Django 4.1.1 on 2022-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_kkomsg_msg_id_kkomsg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicMsgTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_index', models.CharField(max_length=24, verbose_name='차수코드')),
                ('msg_content', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('img_content', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지')),
                ('link_content', models.URLField(blank=True, max_length=512, null=True, verbose_name='외부링크')),
                ('start_at', models.DateTimeField(verbose_name='시작일')),
                ('end_at', models.DateTimeField(verbose_name='종료일')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
            ],
            options={
                'verbose_name': '부가 메시지 템플릿',
                'verbose_name_plural': '부가 메시지 템플릿',
            },
        ),
        migrations.AddField(
            model_name='msgtemplate',
            name='img_content',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='msgtemplate',
            name='link_content',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='외부링크'),
        ),
        migrations.AlterField(
            model_name='kkomsg',
            name='msg_index',
            field=models.CharField(max_length=24, verbose_name='차수코드'),
        ),
        migrations.AlterField(
            model_name='kkomsg',
            name='send_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='요청일시'),
        ),
        migrations.AlterField(
            model_name='msgtemplate',
            name='msg_index',
            field=models.CharField(max_length=24, verbose_name='차수코드'),
        ),
    ]
