# Generated by Django 4.1.1 on 2023-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_publicmsgtemplate_msgtemplate_img_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='report_owner_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='agency',
            name='report_owner_tel',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='담당자 연락처'),
        ),
        migrations.AddField(
            model_name='agency',
            name='report_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='리포트 수신'),
        ),
        migrations.AlterField(
            model_name='kkomsg',
            name='send_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트'),
        ),
    ]
